### PR TITLE
Requirements: isbnid library change

### PR DESCRIPTION
**Pull request by rikirenz**
* Moves from isbnid(0.3.4) to isbnid_fork(0.4.4) library

Signed-off-by: Riccardo Candido <riccardo.candido@gmail.com>

### CODE REVIEW

**Comment by rikirenz** [comment]
@jirikuncar what do you think about this error https://travis-ci.org/inveniosoftware/idutils/jobs/191034262 ?

I have checked the `sphinx` repo and I found this: https://github.com/sphinx-doc/sphinx/pull/2875. I think we can remove the test suit on travis for the Python version 3.3.

**Comment by lnielsen** [comment]
Fine by me to drop 3.3 support. It's anyway in line with inveniosoftware/invenio#3647

**Comment by jirikuncar** [comment]
It is fine to drop 3.3. Shall we start testing 3.6?

**Comment by rikirenz** [comment]
@jirikuncar I have checked and with `Python 3.6` it is working (locally). If you want I can integrate it in order to run the test suit with `Python 3.6` on Travis.

Should I open an other issue or can I directly make an other PR?

**Comment by david-caro** [comment]
Depends on #28

**Comment by jirikuncar** [comment]
@rikirenz can you please rebase the PR?

**Comment by rikirenz** [comment]
Closes #26

**Comment by david-caro** [comment]
Looks good to me

**Pull request merged**
