### PR TITLE
add support for genomic identifiers

### PR DESCRIPTION
**Pull request by afrubin**
I have implemented the validators and url resolvers for several common genomic databases. Each has test cases, and the tests pass when run locally.

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks for the PR - do you have links to some formal descriptions of the identifiers?

**Comment by afrubin** [comment]
Here are links to the formal descriptions that I used to write the validators. URL resolvers were primarily based on information from http://identifiers.org/

I have merged the 1.0.1 changes and corrected the omission of a valid BioProject accession format.

- SRA https://www.ncbi.nlm.nih.gov/books/NBK56913/#search.what_do_the_different_sra_accessi
- BioProject [DDBJ](https://www.ddbj.nig.ac.jp/bioproject/faq-e.html#project-accession) [ENA](https://www.ebi.ac.uk/ena/submit/project-format) [NCBI](https://www.ncbi.nlm.nih.gov/bioproject/docs/faq/#under-what-circumstances-is-it-n)
- BioSample [DDBJ](https://www.ddbj.nig.ac.jp/biosample/faq-e.html) [ENA](http://ena-docs.readthedocs.io/en/latest/prog_03.html#accession-numbers-in-the-receipt-xml) [NCBI](https://www.ncbi.nlm.nih.gov/biosample/docs/submission/faq/)
- Ensembl https://www.ensembl.org/info/genome/stable_ids/prefixes.html
- UniProt https://www.uniprot.org/help/accession_numbers
- RefSeq https://academic.oup.com/nar/article-abstract/44/D1/D733/2502674 (Table 1)
- genome https://www.ebi.ac.uk/ena/browse/genome-assembly-database

NOTE: For the RefSeq validator, the pattern could/should be more strict in terms of the number of digits (6 or 9) following the various prefixes when that is specified by the standard, but it would make the regex quite a bit longer. The `NZ_` pattern is unusual and I couldn't find clear documentation for the format but `NZ_[A-Z]{4}` seems to be correct.

**Comment by afrubin** [comment]
@lnielsen Any update on the status of this PR?

**Comment by lnielsen** [comment]
Sorry for holding up the PR - I'm ready to merge it now, just one last clarification. Who is the legal copyright holder of your contribution? Is it you personally, or is it e.g. your employer?

**Comment by afrubin** [comment]
Thanks for coming back to this!

> Who is the legal copyright holder of your contribution? 
The legal copyright holder is me, Alan F Rubin.

**Pull request merged**
