### PR TITLE
import: adding isbnlib library

### PR DESCRIPTION
**Pull request by ines-cruz**
related to https://github.com/zenodo/zenodo/issues/2220

### CODE REVIEW

**Comment by ppanero** [comment]
@slint @ines-cruz We are getting more tickets in support about this issue, any ETA for merge?

**Comment by slint** [comment]
I'm still a bit hesitant about the removed ISBN test cases... I mean how wrong could we have been when we added them originally... Plus, they seem to resolve properly, so could this be a bug/edge-case in `isbnlib`?

Let's discuss IRL to see who/when can give this priority to close it soon.

**Comment by lnielsen** [comment]
What's the reason for the removal of the test cases?

**Comment by slint** [comment]
> What's the reason for the removal of the test cases? Also, why the removal of the GND case?

Having a look right now, these shouldn't be removed.

**Comment by slint** [comment]
Ok, a big mixup with ISBNs and GNDs is resolved, old test cases were kept, and a new ISBN known to fail on Zenodo was added... 

- GNDs that are clearly GNDs (i.e. have the `gnd:` prefix), will not be detected as valid ISBNs (in case they also happen to be such numbers).
- Added some docs that ISBN10 is normalized to ISBN13 (which was the previous behavior).

**Pull request merged**
